# Generated by Django 4.0.4 on 2022-04-28 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='owner',
        ),
    ]
